// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SmartGarage.Infrastructure.Data;

#nullable disable

namespace SmartGarage.Infrastructure.Migrations
{
    [DbContext(typeof(SmartGarageDbContext))]
    [Migration("20260506151800_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.0");

            modelBuilder.Entity("SmartGarage.Core.Entities.Notification", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsRead")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Notifications");
                });

            modelBuilder.Entity("SmartGarage.Core.Entities.ParkingRate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("DailyRate")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("EffectiveFrom")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("EffectiveTo")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("HourlyRate")
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("MonthlyRate")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("VehicleType")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("ParkingRates");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 5, 6, 15, 17, 59, 567, DateTimeKind.Utc).AddTicks(8627),
                            DailyRate = 30000m,
                            EffectiveFrom = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            HourlyRate = 5000m,
                            IsActive = true,
                            MonthlyRate = 500000m,
                            VehicleType = 0
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2026, 5, 6, 15, 17, 59, 567, DateTimeKind.Utc).AddTicks(8640),
                            DailyRate = 100000m,
                            EffectiveFrom = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            HourlyRate = 20000m,
                            IsActive = true,
                            MonthlyRate = 2000000m,
                            VehicleType = 1
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2026, 5, 6, 15, 17, 59, 567, DateTimeKind.Utc).AddTicks(8643),
                            DailyRate = 10000m,
                            EffectiveFrom = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            HourlyRate = 2000m,
                            IsActive = true,
                            MonthlyRate = 200000m,
                            VehicleType = 2
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2026, 5, 6, 15, 17, 59, 567, DateTimeKind.Utc).AddTicks(8645),
                            DailyRate = 150000m,
                            EffectiveFrom = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            HourlyRate = 30000m,
                            IsActive = true,
                            MonthlyRate = 3000000m,
                            VehicleType = 3
                        });
                });

            modelBuilder.Entity("SmartGarage.Core.Entities.ParkingSpot", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("Floor")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SpotCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<int>("SpotType")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Zone")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("SpotCode")
                        .IsUnique();

                    b.ToTable("ParkingSpots");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Floor = 1,
                            SpotCode = "A101",
                            SpotType = 1,
                            Status = 0,
                            Zone = "A"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Floor = 1,
                            SpotCode = "A102",
                            SpotType = 1,
                            Status = 0,
                            Zone = "A"
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Floor = 1,
                            SpotCode = "A103",
                            SpotType = 1,
                            Status = 0,
                            Zone = "A"
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Floor = 1,
                            SpotCode = "A104",
                            SpotType = 1,
                            Status = 0,
                            Zone = "A"
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Floor = 1,
                            SpotCode = "A105",
                            SpotType = 1,
                            Status = 0,
                            Zone = "A"
                        },
                        new
                        {
                            Id = 6,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Floor = 1,
                            SpotCode = "A106",
                            SpotType = 1,
                            Status = 0,
                            Zone = "A"
                        },
                        new
                        {
                            Id = 7,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Floor = 1,
                            SpotCode = "A107",
                            SpotType = 1,
                            Status = 0,
                            Zone = "A"
                        },
                        new
                        {
                            Id = 8,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Floor = 1,
                            SpotCode = "A108",
                            SpotType = 1,
                            Status = 0,
                            Zone = "A"
                        },
                        new
                        {
                            Id = 9,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Floor = 1,
                            SpotCode = "A109",
                            SpotType = 1,
                            Status = 0,
                            Zone = "A"
                        },
                        new
                        {
                            Id = 10,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Floor = 1,
                            SpotCode = "A110",
                            SpotType = 1,
                            Status = 0,
                            Zone = "A"
                        },
                        new
                        {
                            Id = 11,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Floor = 1,
                            SpotCode = "B101",
                            SpotType = 0,
                            Status = 0,
                            Zone = "B"
                        },
                        new
                        {
                            Id = 12,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Floor = 1,
                            SpotCode = "B102",
                            SpotType = 0,
                            Status = 0,
                            Zone = "B"
                        },
                        new
                        {
                            Id = 13,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Floor = 1,
                            SpotCode = "B103",
                            SpotType = 0,
                            Status = 0,
                            Zone = "B"
                        },
                        new
                        {
                            Id = 14,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Floor = 1,
                            SpotCode = "B104",
                            SpotType = 0,
                            Status = 0,
                            Zone = "B"
                        },
                        new
                        {
                            Id = 15,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Floor = 1,
                            SpotCode = "B105",
                            SpotType = 0,
                            Status = 0,
                            Zone = "B"
                        },
                        new
                        {
                            Id = 16,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Floor = 1,
                            SpotCode = "B106",
                            SpotType = 0,
                            Status = 0,
                            Zone = "B"
                        },
                        new
                        {
                            Id = 17,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Floor = 1,
                            SpotCode = "B107",
                            SpotType = 0,
                            Status = 0,
                            Zone = "B"
                        },
                        new
                        {
                            Id = 18,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Floor = 1,
                            SpotCode = "B108",
                            SpotType = 0,
                            Status = 0,
                            Zone = "B"
                        },
                        new
                        {
                            Id = 19,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Floor = 1,
                            SpotCode = "B109",
                            SpotType = 0,
                            Status = 0,
                            Zone = "B"
                        },
                        new
                        {
                            Id = 20,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Floor = 1,
                            SpotCode = "B110",
                            SpotType = 0,
                            Status = 0,
                            Zone = "B"
                        },
                        new
                        {
                            Id = 21,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Floor = 1,
                            SpotCode = "B111",
                            SpotType = 0,
                            Status = 0,
                            Zone = "B"
                        },
                        new
                        {
                            Id = 22,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Floor = 1,
                            SpotCode = "B112",
                            SpotType = 0,
                            Status = 0,
                            Zone = "B"
                        },
                        new
                        {
                            Id = 23,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Floor = 1,
                            SpotCode = "B113",
                            SpotType = 0,
                            Status = 0,
                            Zone = "B"
                        },
                        new
                        {
                            Id = 24,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Floor = 1,
                            SpotCode = "B114",
                            SpotType = 0,
                            Status = 0,
                            Zone = "B"
                        },
                        new
                        {
                            Id = 25,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Floor = 1,
                            SpotCode = "B115",
                            SpotType = 0,
                            Status = 0,
                            Zone = "B"
                        },
                        new
                        {
                            Id = 26,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Floor = 1,
                            SpotCode = "B116",
                            SpotType = 0,
                            Status = 0,
                            Zone = "B"
                        },
                        new
                        {
                            Id = 27,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Floor = 1,
                            SpotCode = "B117",
                            SpotType = 0,
                            Status = 0,
                            Zone = "B"
                        },
                        new
                        {
                            Id = 28,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Floor = 1,
                            SpotCode = "B118",
                            SpotType = 0,
                            Status = 0,
                            Zone = "B"
                        },
                        new
                        {
                            Id = 29,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Floor = 1,
                            SpotCode = "B119",
                            SpotType = 0,
                            Status = 0,
                            Zone = "B"
                        },
                        new
                        {
                            Id = 30,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Floor = 1,
                            SpotCode = "B120",
                            SpotType = 0,
                            Status = 0,
                            Zone = "B"
                        },
                        new
                        {
                            Id = 31,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Floor = 2,
                            SpotCode = "A201",
                            SpotType = 1,
                            Status = 0,
                            Zone = "A"
                        },
                        new
                        {
                            Id = 32,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Floor = 2,
                            SpotCode = "A202",
                            SpotType = 1,
                            Status = 0,
                            Zone = "A"
                        },
                        new
                        {
                            Id = 33,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Floor = 2,
                            SpotCode = "A203",
                            SpotType = 1,
                            Status = 0,
                            Zone = "A"
                        },
                        new
                        {
                            Id = 34,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Floor = 2,
                            SpotCode = "A204",
                            SpotType = 1,
                            Status = 0,
                            Zone = "A"
                        },
                        new
                        {
                            Id = 35,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Floor = 2,
                            SpotCode = "A205",
                            SpotType = 1,
                            Status = 0,
                            Zone = "A"
                        },
                        new
                        {
                            Id = 36,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Floor = 2,
                            SpotCode = "A206",
                            SpotType = 1,
                            Status = 0,
                            Zone = "A"
                        },
                        new
                        {
                            Id = 37,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Floor = 2,
                            SpotCode = "A207",
                            SpotType = 1,
                            Status = 0,
                            Zone = "A"
                        },
                        new
                        {
                            Id = 38,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Floor = 2,
                            SpotCode = "A208",
                            SpotType = 1,
                            Status = 0,
                            Zone = "A"
                        },
                        new
                        {
                            Id = 39,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Floor = 2,
                            SpotCode = "A209",
                            SpotType = 1,
                            Status = 0,
                            Zone = "A"
                        },
                        new
                        {
                            Id = 40,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Floor = 2,
                            SpotCode = "A210",
                            SpotType = 1,
                            Status = 0,
                            Zone = "A"
                        },
                        new
                        {
                            Id = 41,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Floor = 2,
                            SpotCode = "B201",
                            SpotType = 0,
                            Status = 0,
                            Zone = "B"
                        },
                        new
                        {
                            Id = 42,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Floor = 2,
                            SpotCode = "B202",
                            SpotType = 0,
                            Status = 0,
                            Zone = "B"
                        },
                        new
                        {
                            Id = 43,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Floor = 2,
                            SpotCode = "B203",
                            SpotType = 0,
                            Status = 0,
                            Zone = "B"
                        },
                        new
                        {
                            Id = 44,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Floor = 2,
                            SpotCode = "B204",
                            SpotType = 0,
                            Status = 0,
                            Zone = "B"
                        },
                        new
                        {
                            Id = 45,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Floor = 2,
                            SpotCode = "B205",
                            SpotType = 0,
                            Status = 0,
                            Zone = "B"
                        },
                        new
                        {
                            Id = 46,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Floor = 2,
                            SpotCode = "B206",
                            SpotType = 0,
                            Status = 0,
                            Zone = "B"
                        },
                        new
                        {
                            Id = 47,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Floor = 2,
                            SpotCode = "B207",
                            SpotType = 0,
                            Status = 0,
                            Zone = "B"
                        },
                        new
                        {
                            Id = 48,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Floor = 2,
                            SpotCode = "B208",
                            SpotType = 0,
                            Status = 0,
                            Zone = "B"
                        },
                        new
                        {
                            Id = 49,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Floor = 2,
                            SpotCode = "B209",
                            SpotType = 0,
                            Status = 0,
                            Zone = "B"
                        },
                        new
                        {
                            Id = 50,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Floor = 2,
                            SpotCode = "B210",
                            SpotType = 0,
                            Status = 0,
                            Zone = "B"
                        },
                        new
                        {
                            Id = 51,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Floor = 2,
                            SpotCode = "B211",
                            SpotType = 0,
                            Status = 0,
                            Zone = "B"
                        },
                        new
                        {
                            Id = 52,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Floor = 2,
                            SpotCode = "B212",
                            SpotType = 0,
                            Status = 0,
                            Zone = "B"
                        },
                        new
                        {
                            Id = 53,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Floor = 2,
                            SpotCode = "B213",
                            SpotType = 0,
                            Status = 0,
                            Zone = "B"
                        },
                        new
                        {
                            Id = 54,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Floor = 2,
                            SpotCode = "B214",
                            SpotType = 0,
                            Status = 0,
                            Zone = "B"
                        },
                        new
                        {
                            Id = 55,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Floor = 2,
                            SpotCode = "B215",
                            SpotType = 0,
                            Status = 0,
                            Zone = "B"
                        },
                        new
                        {
                            Id = 56,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Floor = 2,
                            SpotCode = "B216",
                            SpotType = 0,
                            Status = 0,
                            Zone = "B"
                        },
                        new
                        {
                            Id = 57,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Floor = 2,
                            SpotCode = "B217",
                            SpotType = 0,
                            Status = 0,
                            Zone = "B"
                        },
                        new
                        {
                            Id = 58,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Floor = 2,
                            SpotCode = "B218",
                            SpotType = 0,
                            Status = 0,
                            Zone = "B"
                        },
                        new
                        {
                            Id = 59,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Floor = 2,
                            SpotCode = "B219",
                            SpotType = 0,
                            Status = 0,
                            Zone = "B"
                        },
                        new
                        {
                            Id = 60,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Floor = 2,
                            SpotCode = "B220",
                            SpotType = 0,
                            Status = 0,
                            Zone = "B"
                        },
                        new
                        {
                            Id = 61,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Floor = 3,
                            SpotCode = "A301",
                            SpotType = 1,
                            Status = 0,
                            Zone = "A"
                        },
                        new
                        {
                            Id = 62,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Floor = 3,
                            SpotCode = "A302",
                            SpotType = 1,
                            Status = 0,
                            Zone = "A"
                        },
                        new
                        {
                            Id = 63,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Floor = 3,
                            SpotCode = "A303",
                            SpotType = 1,
                            Status = 0,
                            Zone = "A"
                        },
                        new
                        {
                            Id = 64,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Floor = 3,
                            SpotCode = "A304",
                            SpotType = 1,
                            Status = 0,
                            Zone = "A"
                        },
                        new
                        {
                            Id = 65,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Floor = 3,
                            SpotCode = "A305",
                            SpotType = 1,
                            Status = 0,
                            Zone = "A"
                        },
                        new
                        {
                            Id = 66,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Floor = 3,
                            SpotCode = "A306",
                            SpotType = 1,
                            Status = 0,
                            Zone = "A"
                        },
                        new
                        {
                            Id = 67,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Floor = 3,
                            SpotCode = "A307",
                            SpotType = 1,
                            Status = 0,
                            Zone = "A"
                        },
                        new
                        {
                            Id = 68,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Floor = 3,
                            SpotCode = "A308",
                            SpotType = 1,
                            Status = 0,
                            Zone = "A"
                        },
                        new
                        {
                            Id = 69,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Floor = 3,
                            SpotCode = "A309",
                            SpotType = 1,
                            Status = 0,
                            Zone = "A"
                        },
                        new
                        {
                            Id = 70,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Floor = 3,
                            SpotCode = "A310",
                            SpotType = 1,
                            Status = 0,
                            Zone = "A"
                        },
                        new
                        {
                            Id = 71,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Floor = 3,
                            SpotCode = "B301",
                            SpotType = 0,
                            Status = 0,
                            Zone = "B"
                        },
                        new
                        {
                            Id = 72,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Floor = 3,
                            SpotCode = "B302",
                            SpotType = 0,
                            Status = 0,
                            Zone = "B"
                        },
                        new
                        {
                            Id = 73,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Floor = 3,
                            SpotCode = "B303",
                            SpotType = 0,
                            Status = 0,
                            Zone = "B"
                        },
                        new
                        {
                            Id = 74,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Floor = 3,
                            SpotCode = "B304",
                            SpotType = 0,
                            Status = 0,
                            Zone = "B"
                        },
                        new
                        {
                            Id = 75,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Floor = 3,
                            SpotCode = "B305",
                            SpotType = 0,
                            Status = 0,
                            Zone = "B"
                        },
                        new
                        {
                            Id = 76,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Floor = 3,
                            SpotCode = "B306",
                            SpotType = 0,
                            Status = 0,
                            Zone = "B"
                        },
                        new
                        {
                            Id = 77,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Floor = 3,
                            SpotCode = "B307",
                            SpotType = 0,
                            Status = 0,
                            Zone = "B"
                        },
                        new
                        {
                            Id = 78,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Floor = 3,
                            SpotCode = "B308",
                            SpotType = 0,
                            Status = 0,
                            Zone = "B"
                        },
                        new
                        {
                            Id = 79,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Floor = 3,
                            SpotCode = "B309",
                            SpotType = 0,
                            Status = 0,
                            Zone = "B"
                        },
                        new
                        {
                            Id = 80,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Floor = 3,
                            SpotCode = "B310",
                            SpotType = 0,
                            Status = 0,
                            Zone = "B"
                        },
                        new
                        {
                            Id = 81,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Floor = 3,
                            SpotCode = "B311",
                            SpotType = 0,
                            Status = 0,
                            Zone = "B"
                        },
                        new
                        {
                            Id = 82,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Floor = 3,
                            SpotCode = "B312",
                            SpotType = 0,
                            Status = 0,
                            Zone = "B"
                        },
                        new
                        {
                            Id = 83,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Floor = 3,
                            SpotCode = "B313",
                            SpotType = 0,
                            Status = 0,
                            Zone = "B"
                        },
                        new
                        {
                            Id = 84,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Floor = 3,
                            SpotCode = "B314",
                            SpotType = 0,
                            Status = 0,
                            Zone = "B"
                        },
                        new
                        {
                            Id = 85,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Floor = 3,
                            SpotCode = "B315",
                            SpotType = 0,
                            Status = 0,
                            Zone = "B"
                        },
                        new
                        {
                            Id = 86,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Floor = 3,
                            SpotCode = "B316",
                            SpotType = 0,
                            Status = 0,
                            Zone = "B"
                        },
                        new
                        {
                            Id = 87,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Floor = 3,
                            SpotCode = "B317",
                            SpotType = 0,
                            Status = 0,
                            Zone = "B"
                        },
                        new
                        {
                            Id = 88,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Floor = 3,
                            SpotCode = "B318",
                            SpotType = 0,
                            Status = 0,
                            Zone = "B"
                        },
                        new
                        {
                            Id = 89,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Floor = 3,
                            SpotCode = "B319",
                            SpotType = 0,
                            Status = 0,
                            Zone = "B"
                        },
                        new
                        {
                            Id = 90,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Floor = 3,
                            SpotCode = "B320",
                            SpotType = 0,
                            Status = 0,
                            Zone = "B"
                        });
                });

            modelBuilder.Entity("SmartGarage.Core.Entities.ParkingTicket", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CheckInTime")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("CheckOutTime")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("ParkingSpotId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("QrCode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TicketCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("TotalAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("VehicleId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ParkingSpotId");

                    b.HasIndex("TicketCode")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.HasIndex("VehicleId");

                    b.ToTable("ParkingTickets");
                });

            modelBuilder.Entity("SmartGarage.Core.Entities.Payment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("ParkingTicketId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PaymentMethod")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TransactionCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ParkingTicketId")
                        .IsUnique();

                    b.HasIndex("TransactionCode")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("Payments");
                });

            modelBuilder.Entity("SmartGarage.Core.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<int>("Role")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "admin@smartgarage.com",
                            FullName = "Admin",
                            IsActive = true,
                            PasswordHash = "$2a$11$/LAhUzI2r0NPKa3UO68E3edzT22n6AFwJkrJGUUPZ4fzhJTsvZRTy",
                            Phone = "0901234567",
                            Role = 3
                        });
                });

            modelBuilder.Entity("SmartGarage.Core.Entities.Vehicle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Brand")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LicensePlate")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<int>("OwnerId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("VehicleType")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("LicensePlate")
                        .IsUnique();

                    b.HasIndex("OwnerId");

                    b.ToTable("Vehicles");
                });

            modelBuilder.Entity("SmartGarage.Core.Entities.Notification", b =>
                {
                    b.HasOne("SmartGarage.Core.Entities.User", "User")
                        .WithMany("Notifications")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("SmartGarage.Core.Entities.ParkingTicket", b =>
                {
                    b.HasOne("SmartGarage.Core.Entities.ParkingSpot", "ParkingSpot")
                        .WithMany("ParkingTickets")
                        .HasForeignKey("ParkingSpotId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SmartGarage.Core.Entities.User", "User")
                        .WithMany("ParkingTickets")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SmartGarage.Core.Entities.Vehicle", "Vehicle")
                        .WithMany("ParkingTickets")
                        .HasForeignKey("VehicleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ParkingSpot");

                    b.Navigation("User");

                    b.Navigation("Vehicle");
                });

            modelBuilder.Entity("SmartGarage.Core.Entities.Payment", b =>
                {
                    b.HasOne("SmartGarage.Core.Entities.ParkingTicket", "ParkingTicket")
                        .WithOne("Payment")
                        .HasForeignKey("SmartGarage.Core.Entities.Payment", "ParkingTicketId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SmartGarage.Core.Entities.User", "User")
                        .WithMany("Payments")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ParkingTicket");

                    b.Navigation("User");
                });

            modelBuilder.Entity("SmartGarage.Core.Entities.Vehicle", b =>
                {
                    b.HasOne("SmartGarage.Core.Entities.User", "Owner")
                        .WithMany("Vehicles")
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("SmartGarage.Core.Entities.ParkingSpot", b =>
                {
                    b.Navigation("ParkingTickets");
                });

            modelBuilder.Entity("SmartGarage.Core.Entities.ParkingTicket", b =>
                {
                    b.Navigation("Payment");
                });

            modelBuilder.Entity("SmartGarage.Core.Entities.User", b =>
                {
                    b.Navigation("Notifications");

                    b.Navigation("ParkingTickets");

                    b.Navigation("Payments");

                    b.Navigation("Vehicles");
                });

            modelBuilder.Entity("SmartGarage.Core.Entities.Vehicle", b =>
                {
                    b.Navigation("ParkingTickets");
                });
#pragma warning restore 612, 618
        }
    }
}
